### ISSUE TITLE
how to monitor worker processes

### ISSUE THREAD

**Issue by daichi5** [Betterment/delayed#21]
We plan to use 'delayed' as an asynchronous processing worker on Kubernetes pods.
So we need a way to do healthcheck of the worker process and we have the following method to do the healthcheck now.

```
livenessProbe:
    exec:
      command:
        - bash
        - -lc
        - '[[ $(ps aux | grep delayed | grep -v grep | wc -l) > 0 ]]'
```

However, if there is a better method, we would like to adopt it. 
So, do you have any other methods?
I'd like to know it for reference because I saw that you use kubertenes in other issues.
